services:
  # 1. SQL Database
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Kudakwashe@2002
    ports:
      - "1433:1433"

  # 2. C# Backend
  backend:
    build: ./backend
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=BankDB;User Id=sa;Password=Kudakwashe@2002;TrustServerCertificate=True;
    depends_on:
      - db

  # 3. React Frontend
  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend